# Generated by Django 3.0 on 2019-12-02 12:16

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
