# Generated by Django 3.0 on 2019-12-02 12:16

from django.db import migrations, models
import django.db.models.deletion
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='paragraphs',
            field=models.ManyToManyField(through='stories.StoryParagraph', to='stories.Paragraph'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='feature_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storyparagraph',
            name='id',
            field=models.CharField(default=utils.functions.create_id, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storyparagraph',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story'),
        ),
        migrations.AlterUniqueTogether(
            name='storyparagraph',
            unique_together={('story', 'paragraph')},
        ),
    ]
